This project is an modified Version of the Steering PCB from Coffeetrac (https://github.com/Coffeetrac/Autosteer_ESP)

The PCB and Schematic contains a ESP32 Pico Kit as the Brain. The communication beetwen the PCB and the Computer is ensured by
an UDP Connection.

The Schematic also contains a CAN-Bus interface for communications with Joysticks etc. which are already installed in the tractor.
The Software is in work, but the Software of Coffeetrac should also work with two pin changes.

I recommend https://github.com/Coffeetrac/Autosteer_ESP for a better understanding and I also welcome criticism.
